[package]
name = "parser_fuck"
version = "0.1.0"
authors = ["Package <Aditrc@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
batch_oper = "1.2.0"
uuid = { version = "0.8", features = ["serde", "v4"] }